import type { Impact, Trip } from "./types";
export const demoTrips: Trip[] = [
  {
    id: "demo-train",
    category: "TRAIN",
    origin: "Yogyakarta",
    destination: "Solo",
    travelDate: "2026-09-06",
    status: "VERIFIED",
    distanceKm: 65,
    carbonEmissionKg: 0.7924,
    carbonReductionKg: 14.4826,
    baselineEmissionKg: 15.275,
    comparison: { type: "SYSTEM", category: "CAR" },
    distanceSource: "PROOF_DISTANCE",
    aiDecision: "REWARD",
    aiReason:
      "The ticket clearly supports the train journey, route, and travel date. Your reward is calculated by Gopax using the estimated emissions per passenger-kilometer.",
    reward: { id: "demo-reward", amount: 95, status: "AVAILABLE" },
  },
  {
    id: "demo-bus",
    category: "BUS",
    origin: "Blok M",
    destination: "Kota",
    travelDate: "2026-09-05",
    status: "VERIFIED",
    distanceKm: 14,
    carbonEmissionKg: 0.42,
    carbonReductionKg: 2.87,
    comparison: { type: "SYSTEM", category: "CAR" },
    reward: { id: "demo-bus-reward", amount: 89, status: "CLAIMED" },
    aiDecision: "REWARD",
  },
  {
    id: "demo-car",
    category: "CAR",
    origin: "Jakarta",
    destination: "Bekasi",
    travelDate: "2026-09-04",
    status: "VERIFIED",
    distanceKm: 25,
    carbonEmissionKg: 5.875,
    carbonReductionKg: null,
    comparison: null,
    reward: { id: "demo-car-reward", amount: 10, status: "CLAIMED" },
    aiDecision: "REWARD",
  },
];
export const demoImpact: Impact = {
  totalTrips: 3,
  totalCarbonEmissionKg: 7.0874,
  totalCarbonSavedKg: 17.3526,
  totalClaimedGopaxReward: 99,
  totalAvailableGopaxReward: 95,
  carbonSavedCoverage: { comparedTrips: 2, verifiedTrips: 3 },
  transportBreakdown: [
    { category: "TRAIN", count: 1 },
    { category: "BUS", count: 1 },
    { category: "CAR", count: 1 },
  ],
};
